// generated by tools/build_gallery.py — do not edit by hand
const GALLERY_CATEGORIES = ["portraits", "couples", "weddings-events", "families", "concerts"];
const GALLERY_LABELS = {"portraits": "Portraits", "couples": "Couples", "weddings-events": "Weddings & Events", "families": "Families", "concerts": "Concerts"};
const GALLERY = [
 {
  "src": "img/portfolio/portraits/01-lindie.jpg",
  "cat": "portraits",
  "label": "Lindie"
 },
 {
  "src": "img/portfolio/portraits/03-lindie.jpg",
  "cat": "portraits",
  "label": "Lindie"
 },
 {
  "src": "img/portfolio/portraits/04-maddy.jpg",
  "cat": "portraits",
  "label": "Maddy"
 },
 {
  "src": "img/portfolio/portraits/05-maddy.jpg",
  "cat": "portraits",
  "label": "Maddy"
 },
 {
  "src": "img/portfolio/portraits/06-desi.jpg",
  "cat": "portraits",
  "label": "Desi"
 },
 {
  "src": "img/portfolio/portraits/07-desi.jpg",
  "cat": "portraits",
  "label": "Desi"
 },
 {
  "src": "img/portfolio/portraits/08-sage.jpg",
  "cat": "portraits",
  "label": "Sage"
 },
 {
  "src": "img/portfolio/portraits/09-trinity.jpg",
  "cat": "portraits",
  "label": "Trinity"
 },
 {
  "src": "img/portfolio/portraits/10-alyssa.jpg",
  "cat": "portraits",
  "label": "Alyssa"
 },
 {
  "src": "img/portfolio/portraits/11-alyssa.jpg",
  "cat": "portraits",
  "label": "Alyssa"
 },
 {
  "src": "img/portfolio/portraits/12-golden-field.jpg",
  "cat": "portraits",
  "label": "Golden Field"
 },
 {
  "src": "img/portfolio/portraits/13-golden-field.jpg",
  "cat": "portraits",
  "label": "Golden Field"
 },
 {
  "src": "img/portfolio/portraits/14-windswept.jpg",
  "cat": "portraits",
  "label": "Windswept"
 },
 {
  "src": "img/portfolio/portraits/15-with-her-horse.jpg",
  "cat": "portraits",
  "label": "With Her Horse"
 },
 {
  "src": "img/portfolio/portraits/16-meadow.jpg",
  "cat": "portraits",
  "label": "Meadow"
 },
 {
  "src": "img/portfolio/portraits/17-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/18-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/19-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/20-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/21-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/22-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/23-desirae.jpg",
  "cat": "portraits",
  "label": "Desirae"
 },
 {
  "src": "img/portfolio/portraits/24-city-fountain.jpg",
  "cat": "portraits",
  "label": "City Fountain"
 },
 {
  "src": "img/portfolio/portraits/25-city-fountain.jpg",
  "cat": "portraits",
  "label": "City Fountain"
 },
 {
  "src": "img/portfolio/portraits/26-city-fountain.jpg",
  "cat": "portraits",
  "label": "City Fountain"
 },
 {
  "src": "img/portfolio/portraits/27-lakeside-senior.jpg",
  "cat": "portraits",
  "label": "Lakeside Senior"
 },
 {
  "src": "img/portfolio/portraits/28-lakeside-senior.jpg",
  "cat": "portraits",
  "label": "Lakeside Senior"
 },
 {
  "src": "img/portfolio/portraits/29-lakeside-senior.jpg",
  "cat": "portraits",
  "label": "Lakeside Senior"
 },
 {
  "src": "img/portfolio/portraits/30-lakeside-senior.jpg",
  "cat": "portraits",
  "label": "Lakeside Senior"
 },
 {
  "src": "img/portfolio/portraits/31-lakeside-senior.jpg",
  "cat": "portraits",
  "label": "Lakeside Senior"
 },
 {
  "src": "img/portfolio/portraits/32-mountain-lake.jpg",
  "cat": "portraits",
  "label": "Mountain Lake"
 },
 {
  "src": "img/portfolio/portraits/33-mountain-lake.jpg",
  "cat": "portraits",
  "label": "Mountain Lake"
 },
 {
  "src": "img/portfolio/portraits/34-mountain-lake.jpg",
  "cat": "portraits",
  "label": "Mountain Lake"
 },
 {
  "src": "img/portfolio/portraits/35-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/portraits/36-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/portraits/37-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/portraits/38-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/portraits/39-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/portraits/40-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/portraits/41-willow-creek.jpg",
  "cat": "portraits",
  "label": "Willow Creek"
 },
 {
  "src": "img/portfolio/couples/01-tianna--layton.jpg",
  "cat": "couples",
  "label": "Tianna & Layton"
 },
 {
  "src": "img/portfolio/couples/02-tianna--layton.jpg",
  "cat": "couples",
  "label": "Tianna & Layton"
 },
 {
  "src": "img/portfolio/couples/03-tianna--layton.jpg",
  "cat": "couples",
  "label": "Tianna & Layton"
 },
 {
  "src": "img/portfolio/couples/04-eden--will.jpg",
  "cat": "couples",
  "label": "Eden & Will"
 },
 {
  "src": "img/portfolio/couples/05-eden--will.jpg",
  "cat": "couples",
  "label": "Eden & Will"
 },
 {
  "src": "img/portfolio/couples/06-jenicolton.jpg",
  "cat": "couples",
  "label": "Jenicolton"
 },
 {
  "src": "img/portfolio/couples/07-jenicolton.jpg",
  "cat": "couples",
  "label": "Jenicolton"
 },
 {
  "src": "img/portfolio/couples/08-desicaiden.jpg",
  "cat": "couples",
  "label": "Desicaiden"
 },
 {
  "src": "img/portfolio/couples/09-desicaiden.jpg",
  "cat": "couples",
  "label": "Desicaiden"
 },
 {
  "src": "img/portfolio/couples/10-landrie--vaden.jpg",
  "cat": "couples",
  "label": "Landrie & Vaden"
 },
 {
  "src": "img/portfolio/couples/11-landrie--vaden.jpg",
  "cat": "couples",
  "label": "Landrie & Vaden"
 },
 {
  "src": "img/portfolio/couples/12-landrie--vaden.jpg",
  "cat": "couples",
  "label": "Landrie & Vaden"
 },
 {
  "src": "img/portfolio/couples/13-landrie--vaden.jpg",
  "cat": "couples",
  "label": "Landrie & Vaden"
 },
 {
  "src": "img/portfolio/couples/14-landrie--vaden.jpg",
  "cat": "couples",
  "label": "Landrie & Vaden"
 },
 {
  "src": "img/portfolio/couples/15-autumn-engagement.jpg",
  "cat": "couples",
  "label": "Autumn Engagement"
 },
 {
  "src": "img/portfolio/couples/16-autumn-engagement.jpg",
  "cat": "couples",
  "label": "Autumn Engagement"
 },
 {
  "src": "img/portfolio/couples/17-autumn-engagement.jpg",
  "cat": "couples",
  "label": "Autumn Engagement"
 },
 {
  "src": "img/portfolio/couples/18-autumn-engagement.jpg",
  "cat": "couples",
  "label": "Autumn Engagement"
 },
 {
  "src": "img/portfolio/couples/19-autumn-engagement.jpg",
  "cat": "couples",
  "label": "Autumn Engagement"
 },
 {
  "src": "img/portfolio/couples/20-autumn-engagement.jpg",
  "cat": "couples",
  "label": "Autumn Engagement"
 },
 {
  "src": "img/portfolio/couples/21-summer-sunset.jpg",
  "cat": "couples",
  "label": "Summer Sunset"
 },
 {
  "src": "img/portfolio/couples/22-summer-sunset.jpg",
  "cat": "couples",
  "label": "Summer Sunset"
 },
 {
  "src": "img/portfolio/couples/23-summer-sunset.jpg",
  "cat": "couples",
  "label": "Summer Sunset"
 },
 {
  "src": "img/portfolio/couples/24-summer-sunset.jpg",
  "cat": "couples",
  "label": "Summer Sunset"
 },
 {
  "src": "img/portfolio/couples/25-summer-sunset.jpg",
  "cat": "couples",
  "label": "Summer Sunset"
 },
 {
  "src": "img/portfolio/couples/26-pumpkin-patch.jpg",
  "cat": "couples",
  "label": "Pumpkin Patch"
 },
 {
  "src": "img/portfolio/weddings-events/01-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/02-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/03-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/04-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/05-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/06-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/07-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/08-the-pauls.jpg",
  "cat": "weddings-events",
  "label": "The Pauls"
 },
 {
  "src": "img/portfolio/weddings-events/09-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/10-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/11-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/12-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/13-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/14-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/15-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/weddings-events/16-courthouse-elopement.jpg",
  "cat": "weddings-events",
  "label": "Courthouse Elopement"
 },
 {
  "src": "img/portfolio/families/01-family-session.jpg",
  "cat": "families",
  "label": "Family Session"
 },
 {
  "src": "img/portfolio/families/02-family-session.jpg",
  "cat": "families",
  "label": "Family Session"
 },
 {
  "src": "img/portfolio/families/03-family-session.jpg",
  "cat": "families",
  "label": "Family Session"
 },
 {
  "src": "img/portfolio/families/04-family-session.jpg",
  "cat": "families",
  "label": "Family Session"
 },
 {
  "src": "img/portfolio/families/05-family-session.jpg",
  "cat": "families",
  "label": "Family Session"
 },
 {
  "src": "img/portfolio/families/06-family-session.jpg",
  "cat": "families",
  "label": "Family Session"
 },
 {
  "src": "img/portfolio/concerts/01-tobymac.jpg",
  "cat": "concerts",
  "label": "Tobymac"
 },
 {
  "src": "img/portfolio/concerts/02-latto.jpg",
  "cat": "concerts",
  "label": "Latto"
 },
 {
  "src": "img/portfolio/concerts/03-gregory-alan-isakov.jpg",
  "cat": "concerts",
  "label": "Gregory Alan Isakov"
 },
 {
  "src": "img/portfolio/concerts/04-wage-war.jpg",
  "cat": "concerts",
  "label": "Wage War"
 },
 {
  "src": "img/portfolio/concerts/05-leprous.jpg",
  "cat": "concerts",
  "label": "Leprous"
 },
 {
  "src": "img/portfolio/concerts/06-souljaboy.jpg",
  "cat": "concerts",
  "label": "Souljaboy"
 },
 {
  "src": "img/portfolio/concerts/07-orla-gartland.jpg",
  "cat": "concerts",
  "label": "Orla Gartland"
 },
 {
  "src": "img/portfolio/concerts/08-foushee.jpg",
  "cat": "concerts",
  "label": "Foushee"
 }
];
