// generated by tools/build_gallery.py — do not edit by hand
const GALLERY_CATEGORIES = ["seniors", "couples", "concerts"];
const GALLERY = [
 {
  "src": "img/portfolio/seniors/01-lindie.jpg",
  "cat": "seniors",
  "label": "Lindie"
 },
 {
  "src": "img/portfolio/seniors/02-lindie.jpg",
  "cat": "seniors",
  "label": "Lindie"
 },
 {
  "src": "img/portfolio/seniors/03-lindie.jpg",
  "cat": "seniors",
  "label": "Lindie"
 },
 {
  "src": "img/portfolio/seniors/04-maddy.jpg",
  "cat": "seniors",
  "label": "Maddy"
 },
 {
  "src": "img/portfolio/seniors/05-maddy.jpg",
  "cat": "seniors",
  "label": "Maddy"
 },
 {
  "src": "img/portfolio/seniors/06-desi.jpg",
  "cat": "seniors",
  "label": "Desi"
 },
 {
  "src": "img/portfolio/seniors/07-desi.jpg",
  "cat": "seniors",
  "label": "Desi"
 },
 {
  "src": "img/portfolio/seniors/08-sage.jpg",
  "cat": "seniors",
  "label": "Sage"
 },
 {
  "src": "img/portfolio/seniors/09-trinity.jpg",
  "cat": "seniors",
  "label": "Trinity"
 },
 {
  "src": "img/portfolio/seniors/10-alyssa.jpg",
  "cat": "seniors",
  "label": "Alyssa"
 },
 {
  "src": "img/portfolio/seniors/11-alyssa.jpg",
  "cat": "seniors",
  "label": "Alyssa"
 },
 {
  "src": "img/portfolio/couples/01-tianna--layton.jpg",
  "cat": "couples",
  "label": "Tianna & Layton"
 },
 {
  "src": "img/portfolio/couples/02-tianna--layton.jpg",
  "cat": "couples",
  "label": "Tianna & Layton"
 },
 {
  "src": "img/portfolio/couples/03-tianna--layton.jpg",
  "cat": "couples",
  "label": "Tianna & Layton"
 },
 {
  "src": "img/portfolio/couples/04-eden--will.jpg",
  "cat": "couples",
  "label": "Eden & Will"
 },
 {
  "src": "img/portfolio/couples/05-eden--will.jpg",
  "cat": "couples",
  "label": "Eden & Will"
 },
 {
  "src": "img/portfolio/couples/06-jenicolton.jpg",
  "cat": "couples",
  "label": "Jenicolton"
 },
 {
  "src": "img/portfolio/couples/07-jenicolton.jpg",
  "cat": "couples",
  "label": "Jenicolton"
 },
 {
  "src": "img/portfolio/couples/08-desicaiden.jpg",
  "cat": "couples",
  "label": "Desicaiden"
 },
 {
  "src": "img/portfolio/couples/09-desicaiden.jpg",
  "cat": "couples",
  "label": "Desicaiden"
 },
 {
  "src": "img/portfolio/concerts/01-tobymac.jpg",
  "cat": "concerts",
  "label": "Tobymac"
 },
 {
  "src": "img/portfolio/concerts/02-latto.jpg",
  "cat": "concerts",
  "label": "Latto"
 },
 {
  "src": "img/portfolio/concerts/03-gregory-alan-isakov.jpg",
  "cat": "concerts",
  "label": "Gregory Alan Isakov"
 },
 {
  "src": "img/portfolio/concerts/04-wage-war.jpg",
  "cat": "concerts",
  "label": "Wage War"
 },
 {
  "src": "img/portfolio/concerts/05-leprous.jpg",
  "cat": "concerts",
  "label": "Leprous"
 },
 {
  "src": "img/portfolio/concerts/06-souljaboy.jpg",
  "cat": "concerts",
  "label": "Souljaboy"
 },
 {
  "src": "img/portfolio/concerts/07-orla-gartland.jpg",
  "cat": "concerts",
  "label": "Orla Gartland"
 },
 {
  "src": "img/portfolio/concerts/08-foushee.jpg",
  "cat": "concerts",
  "label": "Foushee"
 }
];
