#!/usr/bin/env python3
"""Regenerate js/gallery-data.js from the contents of img/portfolio/.

Usage: python3 tools/build_gallery.py  (run from the website/ root)

Pattern: drop optimized JPGs into img/portfolio/<category>/, named
NN-description.jpg (NN controls display order), then run this script
and commit. Categories appear as filters in the order listed below;
add a new category folder (e.g. weddings/) and it shows up automatically.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PORTFOLIO = os.path.join(ROOT, "img", "portfolio")
OUT = os.path.join(ROOT, "js", "gallery-data.js")

# preferred filter order; unknown folders get appended alphabetically
CATEGORY_ORDER = ["seniors", "couples", "weddings", "families", "headshots", "concerts"]

def label_from_filename(name: str) -> str:
    stem = os.path.splitext(name)[0]
    stem = re.sub(r"^\d+-", "", stem)          # drop NN- ordering prefix
    stem = stem.replace("--", " & ").replace("-", " ")
    return stem.title()

def main() -> None:
    cats = [d for d in sorted(os.listdir(PORTFOLIO))
            if os.path.isdir(os.path.join(PORTFOLIO, d))]
    cats.sort(key=lambda c: (CATEGORY_ORDER.index(c) if c in CATEGORY_ORDER else 99, c))

    items = []
    for cat in cats:
        d = os.path.join(PORTFOLIO, cat)
        for f in sorted(os.listdir(d)):
            if f.lower().endswith((".jpg", ".jpeg", ".webp", ".png")):
                items.append({
                    "src": f"img/portfolio/{cat}/{f}",
                    "cat": cat,
                    "label": label_from_filename(f),
                })

    with open(OUT, "w") as fh:
        fh.write("// generated by tools/build_gallery.py — do not edit by hand\n")
        fh.write(f"const GALLERY_CATEGORIES = {json.dumps(cats)};\n")
        fh.write(f"const GALLERY = {json.dumps(items, indent=1)};\n")
    print(f"{len(items)} images across {len(cats)} categories -> {os.path.relpath(OUT, ROOT)}")

if __name__ == "__main__":
    main()
